### ISSUE TITLE
CUDA kernel compilation failed

### ISSUE THREAD

**Issue by greendddd** [zju3dv/pvnet-rendering#26]
Hi, something went wrong with CUDA version when rendering.
I am using Ubuntu18.04, GTX1660Ti, nvidia driver430, CUDA9, and blender2.79a.

The error message is as follow:
CUDA version 9.10 detected, build may succeed but only CUDA 8.0 is officially supported.
Compiling CUDA kernel ...
"/usr/local/cuda/bin/nvcc" -arch=sm_75 --cubin "/home/username/lib/blender2.79a/2.79/scripts/addons/cycles/source/kernel/kernels/cuda/kernel.cu" -o "/home/username/.cache/cycles/kernels/cycles_kernel_sm75_9738CB424246C25C69BDF166A1B9BDD7.cubin" -m64 --ptxas-options="-v" --use_fast_math -DNVCC -D__KERNEL_CUDA_VERSION__=90 -I"/home/username/lib/blender2.79a/2.79/scripts/addons/cycles/source"
nvcc fatal   : Value 'sm_75' is not defined for option 'gpu-architecture'
CUDA kernel compilation failed, see console for details.

Could you help me solve this problem? Thanks very much.

**Comment by pengsida** [comment]
CUDA version 9.10 detected, build may succeed but only CUDA 8.0 is officially supported.
Use cuda 8.0.

**Comment by greendddd** [comment]
Thanks for the help. Finally, I solved this problem by changing CUDA9 to CUDA10. For GTX1660ti or RTX GPUs, the only option is to use CUDA10(and pytorch1.1 instead of 0.4.1). Despite the warning of blender2.79a, it actually works fine with CUDA versions higher than 8.0.
